# Generated by Django 4.2.2 on 2023-06-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_descripcion_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='genero',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='item',
            name='titulo',
        ),
    ]
